### ISSUE TITLE
fc-warm 插件

### ISSUE THREAD

**Issue by heimanba** [devsapp/keep-warm-fc#1]
设计格式为
```
fc-nas-filemgr: # 业务名称/模块名称
    component: fc # 组件名称
    actions:
      post-deploy:
        # 请注意这里上传的路径，如果之前已经挂载了这个nas，并且上传过这个文件夹，会导致文件的覆盖
        - plugin: fc-warm
          args: 
            warm-url: http:www.baidu.com
            warm-interval: 2m
```
